
package Getudiant;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Getudiant_form extends javax.swing.JFrame {

ArrayList<Etudiant> etudiants= new ArrayList<>();//list des etudiants
//cette ArrayList a été trés utile dans le code du boutons trouvé
DefaultTableModel modele;/*objet pour ajouter,suppromer ou modifier 
les lignes du tableau etudiant*/

    public Getudiant_form() {
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAjouter = new javax.swing.JButton();
        btModifier = new javax.swing.JButton();
        btSupprimer = new javax.swing.JButton();
        btVider = new javax.swing.JButton();
        btTrouver = new javax.swing.JButton();
        btnquitter = new javax.swing.JButton();
        btnSauvegarder = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btAdmis = new javax.swing.JButton();
        btTous = new javax.swing.JButton();
        btEchec = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMoyenne = new javax.swing.JTextField();
        txtMatricule = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        cbSexe = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEtudiant = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        btAjouter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btAjouter.setText("Ajouter");
        btAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterActionPerformed(evt);
            }
        });

        btModifier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btModifier.setText("Modifier");
        btModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifierActionPerformed(evt);
            }
        });

        btSupprimer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSupprimer.setText("Supprimer");
        btSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerActionPerformed(evt);
            }
        });

        btVider.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btVider.setText("Vider");
        btVider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViderActionPerformed(evt);
            }
        });

        btTrouver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btTrouver.setText("Trouver");
        btTrouver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTrouverActionPerformed(evt);
            }
        });

        btnquitter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnquitter.setText("Quitter");
        btnquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitterActionPerformed(evt);
            }
        });

        btnSauvegarder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSauvegarder.setText("Sauvegarder");
        btnSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauvegarderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnquitter, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSupprimer)
                            .addComponent(btVider, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btTrouver, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSauvegarder)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btVider, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btTrouver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSauvegarder, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnquitter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(550, 30, 220, 360);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        btAdmis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btAdmis.setText("Admis");
        btAdmis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdmisActionPerformed(evt);
            }
        });

        btTous.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btTous.setText("Tous");
        btTous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTousActionPerformed(evt);
            }
        });

        btEchec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btEchec.setText("Echec");
        btEchec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEchecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btAdmis, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btEchec, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btTous, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdmis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTous, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEchec, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 500, 540, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Moyenne Générale");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 230, 190, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Matricule Etudiant");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 180, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Nom Etudiant");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 140, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Sexe Etudiant");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 150, 50);

        txtMoyenne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoyenneActionPerformed(evt);
            }
        });
        getContentPane().add(txtMoyenne);
        txtMoyenne.setBounds(260, 240, 200, 40);

        txtMatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculeActionPerformed(evt);
            }
        });
        getContentPane().add(txtMatricule);
        txtMatricule.setBounds(260, 40, 190, 40);

        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        getContentPane().add(txtNom);
        txtNom.setBounds(260, 110, 190, 40);

        cbSexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        getContentPane().add(cbSexe);
        cbSexe.setBounds(260, 180, 190, 30);

        tableEtudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricule Etudiant", "Nom Etudiant", "Type", "Moyenne Générale"
            }
        ));
        tableEtudiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEtudiantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEtudiant);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 310, 460, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMoyenneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoyenneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoyenneActionPerformed

    private void txtMatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculeActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your andling code here:
    }//GEN-LAST:event_txtNomActionPerformed
//////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////traitement des boutons/////////////////////////////////
    
    private void btAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterActionPerformed
        ajouterEtudiant(); 
    }//GEN-LAST:event_btAjouterActionPerformed

    private void btSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerActionPerformed
        modele = (DefaultTableModel)tableEtudiant.getModel();
        int ligne =tableEtudiant.getSelectedRow();
        if(ligne!=-1){

            etudiants.remove(ligne);//supprimer l'etudiant de ArrayList
            modele.removeRow(ligne);//supprimer l'etudiant du tableau  

            viderChamp();
        }
    }//GEN-LAST:event_btSupprimerActionPerformed

    private void btViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViderActionPerformed
        modele=(DefaultTableModel) tableEtudiant.getModel();
        viderChamp();
        //cette boucle permet de vider le tableau
        for(int i=modele.getRowCount()-1;i>=0;i--){
             etudiants.get(i).setId(0);
            modele.removeRow(i);//vider le tableau
            etudiants.remove(i);//vider arraylist   
        }
        
       
    }//GEN-LAST:event_btViderActionPerformed

    private void btModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifierActionPerformed
        modele=(DefaultTableModel) tableEtudiant.getModel();
        int ligne = tableEtudiant.getSelectedRow();
        if(ligne!=-1 && !txtMatricule.getText().isEmpty()&& !txtNom.getText().isEmpty()&& !txtMoyenne.getText().isEmpty()){
            //modifier dans le tableau
            modele.setValueAt(txtMatricule.getText(),ligne, 0);
            modele.setValueAt(txtNom.getText(),ligne, 1);
            modele.setValueAt(cbSexe.getSelectedItem(),ligne, 2);
            modele.setValueAt(txtMoyenne.getText(),ligne, 3);  
            //modifier dans arrayList
            etudiants.get(ligne).setMatricule(txtMatricule.getText());
            etudiants.get(ligne).setNom(txtNom.getText());
            etudiants.get(ligne).setSexe(cbSexe.getSelectedItem().toString());
            etudiants.get(ligne). setNotemoyen(Float.parseFloat(txtMoyenne.getText())); 
            viderChamp();
        }
       
    }//GEN-LAST:event_btModifierActionPerformed
//cette methode paermet d'ajouter le matricule et le nom dans leur champs lors de les selectionner dans le tableau
    private void tableEtudiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEtudiantMouseClicked
      modele=(DefaultTableModel) tableEtudiant.getModel();
        int ligne = tableEtudiant.getSelectedRow();
        if(ligne!=-1){
            txtMatricule.setText(etudiants.get(ligne).getMatricule());
            txtNom.setText(etudiants.get(ligne).getNom());
            float note=etudiants.get(ligne).getNotemoyen();
            txtMoyenne.setText(String.valueOf(note));        }
    }//GEN-LAST:event_tableEtudiantMouseClicked

    private void btnquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnquitterActionPerformed

    private void btTrouverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTrouverActionPerformed
       modele = (DefaultTableModel) tableEtudiant.getModel();
        String mtrEtudiant = JOptionPane.showInputDialog(this,"Entrer le matricule Etudiant");
        boolean trouvé=false;
        int indice=0;
        for(int i=0;i<etudiants.size();i++){
Etudiant e = etudiants.get(i);
//creation d'un objet a chaque fois afin de comprer son matricule avec celui saisi
            if(mtrEtudiant.equals(e.getMatricule())){
                trouvé=true;
                indice=i;
/*on doit recupérer l'indice pour qu'on puisse l'utiliser pour recupérer le matricule
chercher de ArrayList et metre les infos convenables dans les champs convenables*/
                break;
            }
        }
        if(trouvé){
            txtMatricule.setText(etudiants.get(indice).getMatricule());
            txtNom.setText(etudiants.get(indice).getNom());
            float note=etudiants.get(indice).getNotemoyen();
            txtMoyenne.setText(String.valueOf(note));
            tableEtudiant.setRowSelectionInterval(indice, indice);
//intervale de la recherche afin de selectionner la ligne rechercher
        }else{
JOptionPane.showMessageDialog(this,"Etudiant introuvable","matricule invalide",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btTrouverActionPerformed

    private void btnSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauvegarderActionPerformed
        
      
             File Detudiant = new File("c:/Etudiant");
        if(Detudiant.exists()!=true){
                Detudiant.mkdir();  
        }
        File fetudiant = new File("c:/Etudiant/Etudiant.data");
            FileWriter fw;
            try {
                fw = new FileWriter(fetudiant,true);
                //BufferedWriter bw = new BufferedWriter(fw);
                for(Etudiant e:etudiants){
                fw.write(e.getMatricule());
                fw.write("\t");
                fw.write(e.getNom());
                fw.write("\t");
                fw.write(e.getSexe());
                fw.write("\t");
                float note = e.getNotemoyen();
                fw.write(String.valueOf(note));
                fw.write("\n");
                }
                fw.close();
                
            } catch (IOException ex) {
                Logger.getLogger(Getudiant_form.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    
    }//GEN-LAST:event_btnSauvegarderActionPerformed

    private void btAdmisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdmisActionPerformed
        
        modele=(DefaultTableModel) tableEtudiant.getModel();
          for(int j=modele.getRowCount()-1;j>=0;j--){
            modele.removeRow(j);//vider le tableau
        }
        for(Etudiant e:etudiants){
        if(e.getNotemoyen()>=10){
         
             modele.addRow(new Object[]{
             e.getMatricule(),
             e.getNom(),
             e.getSexe(),
             e.getNotemoyen()});
        }
        
    }
        
        
    }//GEN-LAST:event_btAdmisActionPerformed

    private void btEchecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEchecActionPerformed
   modele=(DefaultTableModel) tableEtudiant.getModel();
          for(int j=modele.getRowCount()-1;j>=0;j--){
            modele.removeRow(j);//vider le tableau
        }
        for(Etudiant e:etudiants){
        
        if(e.getNotemoyen()<10){
         
          modele.addRow(new Object[]{e.getMatricule(),
             e.getNom(),
             e.getSexe(),
             e.getNotemoyen()});  
        }
       
    }    }//GEN-LAST:event_btEchecActionPerformed

    private void btTousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTousActionPerformed
        modele=(DefaultTableModel) tableEtudiant.getModel();
            for(int j=modele.getRowCount()-1;j>=0;j--){
            modele.removeRow(j);//vider le tableau
        }
        for(Etudiant e:etudiants){
         
         modele.addRow(new Object[]{e.getMatricule(),
             e.getNom(),
             e.getSexe(),
             e.getNotemoyen()}); 
         
     
    }//GEN-LAST:event_btTousActionPerformed
    }
    
//////////////////////////////////////////////////////////////////////////////////////////
 ////////////////////////////////////////////////////////////////////////////////////////   
 ////////////////////////////////////////////////////////////////////////////////////////   
 /////////////////////////////////////////////////////////////////////////////////////// 
////////////////////////////////DECLARATION DES METHODES/////////////////////////////
    ///////////////methode ajouter etudiant/////////////////////////////////////////////
    private void ajouterEtudiant(){
   modele =(DefaultTableModel) tableEtudiant.getModel();
   boolean ajout=true;
   if(txtMatricule.getText().equals("") &&txtNom.getText().equals("") && txtMoyenne.getText().equals("")){
       JOptionPane.showMessageDialog(this,"Remplissez tous les champs SVP","champs vides",JOptionPane.ERROR_MESSAGE);
  ajout = false;
   }
   
   //cette boucle permet d'eviter la duplication d'un etudiant par l'utilisateur
   for(Etudiant e:etudiants){
       if(e.getMatricule().equals(txtMatricule.getText())|| e.getNom().equals(txtNom.getText())){
           
    JOptionPane.showMessageDialog(this,"cet etudiant est déja existe","eleve existant",JOptionPane.HEIGHT);
    ajout=false;
    //////////vider le contenue des txtfield si l'etudiant est deja existe
                viderChamp();
       }
   }
   if(ajout){
 Etudiant etudiant =new Etudiant(txtMatricule.getText(),txtNom.getText(),Float.parseFloat(txtMoyenne.getText()),cbSexe.getSelectedItem().toString());
       
etudiants.add(etudiant);////////////////////////ajouter dans arraylist
///////////////////////ajouter dans le tableau de la fenétre du design
modele.addRow(new Object[]{etudiant.getMatricule(),
        etudiant.getNom(),etudiant.getSexe(),
        etudiant.getNotemoyen()});
//////////vider le contenue des txtfield apres avoir cliquer sur ajouter
            viderChamp();
   }
}
                 /////////////////////////////////////////////////////////////
                /////////////////////////////////////////////////////////////
    ///////////////////methode pour vider les champs///////////////////////////////////
     private void viderChamp() {
        txtMatricule.setText("");
        txtNom.setText("");
        txtMoyenne.setText("");
        txtMatricule.requestFocus();
    }

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Getudiant_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Getudiant_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Getudiant_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Getudiant_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Getudiant_form eleve= new Getudiant_form();
               eleve.setTitle("gestion des etudiants");
               eleve.setResizable(true);
               eleve.setLocationRelativeTo(null);
               eleve.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdmis;
    private javax.swing.JButton btAjouter;
    private javax.swing.JButton btEchec;
    private javax.swing.JButton btModifier;
    private javax.swing.JButton btSupprimer;
    private javax.swing.JButton btTous;
    private javax.swing.JButton btTrouver;
    private javax.swing.JButton btVider;
    private javax.swing.JButton btnSauvegarder;
    private javax.swing.JButton btnquitter;
    private javax.swing.JComboBox<String> cbSexe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEtudiant;
    private javax.swing.JTextField txtMatricule;
    private javax.swing.JTextField txtMoyenne;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
